//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.19.0
//     from Assets/Input/FlightControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Flusi
{
    /// <summary>
    /// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Input/FlightControls.inputactions".
    /// </summary>
    /// <remarks>
    /// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
    /// </remarks>
    /// <example>
    /// <code>
    /// using namespace UnityEngine;
    /// using UnityEngine.InputSystem;
    ///
    /// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
    /// public class Example : MonoBehaviour, MyActions.IPlayerActions
    /// {
    ///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
    ///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
    ///
    ///     void Awake()
    ///     {
    ///         m_Actions = new MyActions_Actions();              // Create asset object.
    ///         m_Player = m_Actions.Player;                      // Extract action map object.
    ///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
    ///     }
    ///
    ///     void OnDestroy()
    ///     {
    ///         m_Actions.Dispose();                              // Destroy asset object.
    ///     }
    ///
    ///     void OnEnable()
    ///     {
    ///         m_Player.Enable();                                // Enable all actions within map.
    ///     }
    ///
    ///     void OnDisable()
    ///     {
    ///         m_Player.Disable();                               // Disable all actions within map.
    ///     }
    ///
    ///     #region Interface implementation of MyActions.IPlayerActions
    ///
    ///     // Invoked when "Move" action is either started, performed or canceled.
    ///     public void OnMove(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
    ///     }
    ///
    ///     // Invoked when "Attack" action is either started, performed or canceled.
    ///     public void OnAttack(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
    ///     }
    ///
    ///     #endregion
    /// }
    /// </code>
    /// </example>
    public partial class @FlightControls: IInputActionCollection2, IDisposable
    {
        /// <summary>
        /// Provides access to the underlying asset instance.
        /// </summary>
        public InputActionAsset asset { get; }

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public @FlightControls()
        {
            asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""FlightControls"",
    ""maps"": [
        {
            ""name"": ""Flight"",
            ""id"": ""88e45e9b-0706-4e99-be58-e7e655a3d444"",
            ""actions"": [
                {
                    ""name"": ""Pitch"",
                    ""type"": ""Value"",
                    ""id"": ""a4ffacc0-3da1-428e-8af4-0de7b491ac22"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Turn"",
                    ""type"": ""Value"",
                    ""id"": ""809fbe42-639a-4ebd-b74c-1e22c3c9af24"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Throttle"",
                    ""type"": ""Value"",
                    ""id"": ""07802ae1-0726-430e-8c7a-ee1a90e11ba0"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""OrbitLook"",
                    ""type"": ""Value"",
                    ""id"": ""8efb91fe-c819-49f1-9bb5-e94e2f85c378"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ToggleAutoLevel"",
                    ""type"": ""Button"",
                    ""id"": ""05742096-ced4-4d71-ab0b-9a84bec27f55"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleView"",
                    ""type"": ""Button"",
                    ""id"": ""ebd5b8c7-a2f0-4a2d-abda-c7464c19102f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleGear"",
                    ""type"": ""Button"",
                    ""id"": ""3f0c1a52-9b7e-4d61-8a4c-2e5b90d7c118"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1DAxis"",
                    ""id"": ""6d94e2ad-b800-4447-a0b0-d4ac5479eedf"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pitch"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""173a9032-3a4b-45d6-9f05-36a6ccb50fdd"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pitch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""7aac923a-a089-4c4a-b116-ff27d125ae7d"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pitch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1DAxis"",
                    ""id"": ""45734533-0956-4e05-80ce-e64e24a9fe8f"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Turn"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""846da2ab-20a9-455c-b1f5-dab62961fbd5"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Turn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""ab914b78-759e-4147-9b74-e9738c98b827"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Turn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1DAxis"",
                    ""id"": ""86f655dd-cf9e-4751-adec-115c0ec34d48"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throttle"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""f668f199-0eb0-4ab2-bca3-ee0082c2fb49"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throttle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""5ca67d46-1a31-4d52-8dde-e5c197b3cd42"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throttle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1DAxis"",
                    ""id"": ""0cb9a080-8c97-4bfb-80e1-db04aaf6c5aa"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OrbitLook"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""c886eca1-6a51-46a5-9380-63523b8bf0a6"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OrbitLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""28e68a08-8c85-4ec9-924b-32a186af5650"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OrbitLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""612e23a0-6a91-40f6-8846-ff89269a6254"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleAutoLevel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6e9deca2-5296-43ae-9c83-ff095909cc50"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b71d4e39-0c86-49f2-95a3-6d148ae2c503"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleGear"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Flight
            m_Flight = asset.FindActionMap("Flight", throwIfNotFound: true);
            m_Flight_Pitch = m_Flight.FindAction("Pitch", throwIfNotFound: true);
            m_Flight_Turn = m_Flight.FindAction("Turn", throwIfNotFound: true);
            m_Flight_Throttle = m_Flight.FindAction("Throttle", throwIfNotFound: true);
            m_Flight_OrbitLook = m_Flight.FindAction("OrbitLook", throwIfNotFound: true);
            m_Flight_ToggleAutoLevel = m_Flight.FindAction("ToggleAutoLevel", throwIfNotFound: true);
            m_Flight_ToggleView = m_Flight.FindAction("ToggleView", throwIfNotFound: true);
            m_Flight_ToggleGear = m_Flight.FindAction("ToggleGear", throwIfNotFound: true);
        }

        ~@FlightControls()
        {
            UnityEngine.Debug.Assert(!m_Flight.enabled, "This will cause a leak and performance issues, FlightControls.Flight.Disable() has not been called.");
        }

        /// <summary>
        /// Destroys this asset and all associated <see cref="InputAction"/> instances.
        /// </summary>
        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
        public void Enable()
        {
            asset.Enable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
        public void Disable()
        {
            asset.Disable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
        public IEnumerable<InputBinding> bindings => asset.bindings;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Flight
        private readonly InputActionMap m_Flight;
        private List<IFlightActions> m_FlightActionsCallbackInterfaces = new List<IFlightActions>();
        private readonly InputAction m_Flight_Pitch;
        private readonly InputAction m_Flight_Turn;
        private readonly InputAction m_Flight_Throttle;
        private readonly InputAction m_Flight_OrbitLook;
        private readonly InputAction m_Flight_ToggleAutoLevel;
        private readonly InputAction m_Flight_ToggleView;
        private readonly InputAction m_Flight_ToggleGear;
        /// <summary>
        /// Provides access to input actions defined in input action map "Flight".
        /// </summary>
        public struct FlightActions
        {
            private @FlightControls m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public FlightActions(@FlightControls wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "Flight/Pitch".
            /// </summary>
            public InputAction @Pitch => m_Wrapper.m_Flight_Pitch;
            /// <summary>
            /// Provides access to the underlying input action "Flight/Turn".
            /// </summary>
            public InputAction @Turn => m_Wrapper.m_Flight_Turn;
            /// <summary>
            /// Provides access to the underlying input action "Flight/Throttle".
            /// </summary>
            public InputAction @Throttle => m_Wrapper.m_Flight_Throttle;
            /// <summary>
            /// Provides access to the underlying input action "Flight/OrbitLook".
            /// </summary>
            public InputAction @OrbitLook => m_Wrapper.m_Flight_OrbitLook;
            /// <summary>
            /// Provides access to the underlying input action "Flight/ToggleAutoLevel".
            /// </summary>
            public InputAction @ToggleAutoLevel => m_Wrapper.m_Flight_ToggleAutoLevel;
            /// <summary>
            /// Provides access to the underlying input action "Flight/ToggleView".
            /// </summary>
            public InputAction @ToggleView => m_Wrapper.m_Flight_ToggleView;
            /// <summary>
            /// Provides access to the underlying input action "Flight/ToggleGear".
            /// </summary>
            public InputAction @ToggleGear => m_Wrapper.m_Flight_ToggleGear;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_Flight; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="FlightActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(FlightActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="FlightActions" />
            public void AddCallbacks(IFlightActions instance)
            {
                if (instance == null || m_Wrapper.m_FlightActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_FlightActionsCallbackInterfaces.Add(instance);
                @Pitch.started += instance.OnPitch;
                @Pitch.performed += instance.OnPitch;
                @Pitch.canceled += instance.OnPitch;
                @Turn.started += instance.OnTurn;
                @Turn.performed += instance.OnTurn;
                @Turn.canceled += instance.OnTurn;
                @Throttle.started += instance.OnThrottle;
                @Throttle.performed += instance.OnThrottle;
                @Throttle.canceled += instance.OnThrottle;
                @OrbitLook.started += instance.OnOrbitLook;
                @OrbitLook.performed += instance.OnOrbitLook;
                @OrbitLook.canceled += instance.OnOrbitLook;
                @ToggleAutoLevel.started += instance.OnToggleAutoLevel;
                @ToggleAutoLevel.performed += instance.OnToggleAutoLevel;
                @ToggleAutoLevel.canceled += instance.OnToggleAutoLevel;
                @ToggleView.started += instance.OnToggleView;
                @ToggleView.performed += instance.OnToggleView;
                @ToggleView.canceled += instance.OnToggleView;
                @ToggleGear.started += instance.OnToggleGear;
                @ToggleGear.performed += instance.OnToggleGear;
                @ToggleGear.canceled += instance.OnToggleGear;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="FlightActions" />
            private void UnregisterCallbacks(IFlightActions instance)
            {
                @Pitch.started -= instance.OnPitch;
                @Pitch.performed -= instance.OnPitch;
                @Pitch.canceled -= instance.OnPitch;
                @Turn.started -= instance.OnTurn;
                @Turn.performed -= instance.OnTurn;
                @Turn.canceled -= instance.OnTurn;
                @Throttle.started -= instance.OnThrottle;
                @Throttle.performed -= instance.OnThrottle;
                @Throttle.canceled -= instance.OnThrottle;
                @OrbitLook.started -= instance.OnOrbitLook;
                @OrbitLook.performed -= instance.OnOrbitLook;
                @OrbitLook.canceled -= instance.OnOrbitLook;
                @ToggleAutoLevel.started -= instance.OnToggleAutoLevel;
                @ToggleAutoLevel.performed -= instance.OnToggleAutoLevel;
                @ToggleAutoLevel.canceled -= instance.OnToggleAutoLevel;
                @ToggleView.started -= instance.OnToggleView;
                @ToggleView.performed -= instance.OnToggleView;
                @ToggleView.canceled -= instance.OnToggleView;
                @ToggleGear.started -= instance.OnToggleGear;
                @ToggleGear.performed -= instance.OnToggleGear;
                @ToggleGear.canceled -= instance.OnToggleGear;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="FlightActions.UnregisterCallbacks(IFlightActions)" />.
            /// </summary>
            /// <seealso cref="FlightActions.UnregisterCallbacks(IFlightActions)" />
            public void RemoveCallbacks(IFlightActions instance)
            {
                if (m_Wrapper.m_FlightActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="FlightActions.AddCallbacks(IFlightActions)" />
            /// <seealso cref="FlightActions.RemoveCallbacks(IFlightActions)" />
            /// <seealso cref="FlightActions.UnregisterCallbacks(IFlightActions)" />
            public void SetCallbacks(IFlightActions instance)
            {
                foreach (var item in m_Wrapper.m_FlightActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_FlightActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="FlightActions" /> instance referencing this action map.
        /// </summary>
        public FlightActions @Flight => new FlightActions(this);
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Flight" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="FlightActions.AddCallbacks(IFlightActions)" />
        /// <seealso cref="FlightActions.RemoveCallbacks(IFlightActions)" />
        public interface IFlightActions
        {
            /// <summary>
            /// Method invoked when associated input action "Pitch" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnPitch(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Turn" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnTurn(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Throttle" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnThrottle(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "OrbitLook" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnOrbitLook(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "ToggleAutoLevel" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnToggleAutoLevel(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "ToggleView" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnToggleView(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "ToggleGear" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnToggleGear(InputAction.CallbackContext context);
        }
    }
}
